export const APP_BACKGROUND = "#FFFFFF";

export const CONTENT_BACKGROUND = "#FFFFFF";

export const NAVBAR_BACKGROUND = "#000000";

export const BUTTON_COLOR_DEFAULT = "#FFFFFF";
export const BUTTON_COLOR_PRIMARY = "#f41d12";
export const BUTTON_COLOR_PRIMARY_HOVER = "#000000";

export const SETTINGS_BUTTON_BACKGROUND_HOVER = "#5C5C5C";
export const SETTINGS_BUTTON_COLOR_HOVER = "#000000";

export const SETTINGS_LIST_ITEM_BACKGROUND = "#F8F8F8";
export const SETTINGS_LIST_ITEM_BACKGROUND_HOVER = "#D8D8D8";
export const SETTINGS_LIST_ITEM_COLOR = "#000000";

export const BOARD_SEPARATOR_BACKGROUND = "#F8F8F8";
